### ISSUE TITLE
Appears to be connecting to incorrect host

### ISSUE THREAD

**Issue by MattByName** [D3rHase/ssh-command-action#9]
Hi there,

Recently this action has stopped working for me with a Remote Host Identification warning. The fingerprint doesn't seem to have changed, and the error message reports a different fingerprint to the host that also seems to be the new GitHub fingerprint:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s.
Please contact your system administrator.
Add correct host key in /home/***/.ssh/known_hosts to get rid of this message.
Offending RSA key in /home/***/.ssh/known_hosts:1
RSA host key for github.com has changed and you have requested strict checking.
Host key verification failed.
```
Googling `uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s.` matches the fingerprint in quoted errors from when Github changed their RSA SSH host key earlier this year.

**Comment by D3rHase** [comment]
Hi Matt, thanks for reporting this. I will look into it

**Comment by MattByName** [comment]
Hi there, I've realised this was my fault! The ssh warning was being thrown by the destination server not by the github environment. Now that I've updated the fingerprint on the destination server everything is working fine .
